import {
  getDivisions,
  updateDivision,
  createDivision,
  removeDivision,
  getGroupTypes,
  getGroups,
  getGroup,
  createGroup,
  updateGroup,
  removeGroup,
  getRules,
  getRule,
  createRule,
  updateRule,
  removeRule,
  getTargets,
  assignTarget,
  updateTarget,
  revokeTarget,
} from "../api/finance";

export const financeService = {
  getDivisions,
  createDivision,
  updateDivision,
  removeDivision,
  getGroupTypes,
  getGroups,
  getGroup,
  createGroup,
  updateGroup,
  removeGroup,
  getRules,
  getRule,
  createRule,
  updateRule,
  removeRule,
  getTargets,
  assignTarget,
  updateTarget,
  revokeTarget,
};
