export type PermissionName =
  | 'system:health:read'
  | 'user:create'
  | 'user:read'
  | 'user:update'
  | 'user:delete'
  | 'user:manage_admin'
  | 'role:create'
  | 'role:read'
  | 'role:update'
  | 'role:delete'
  | 'user_role:assign'
  | 'user_role:revoke'
  | 'user_role:read'
  | 'role_permission:assign'
  | 'role_permission:revoke'
  | 'role_permission:read'
  | 'permission:read'
  | 'counter_update:create'
  | 'counter_update:read'
  | 'counter_update:update'
  | 'counter_update:delete'
  | 'product_prices:read'
  // placeholders: no backend endpoints yet, kept so Groups/Rules nav items can compile
  | 'groups:read'
  | 'rules:read'

export type Permission = { id: number; name: string }
